### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 21: invalid continuation byte

### ISSUE THREAD

**Issue by wuhongsheng** [jamm1985/seismo-performer#15]
I try 
input = "./test/archives/NYSH.IM.00.EHE.2021.091"
 archives = stools.parse_archive_csv(input) 
output error

**Comment by Syler1984** [comment]
Hello, the `test/archives` files are **mseed** files. Each of them represents a waveform data channel. These archives are dated April 4, 2021 and contain a verified seismic event at around 12:36:00.

`stools.parche_archive_csv` is an internal function that just parses a _csv_ file with archives names. You can lookup [this file](https://github.com/jamm1985/seismo-performer/tree/main/test/nysh_archives.txt) as an example.

The error is caused by trying to pass **mseed** file instead of **csv** file to `stools.parche_archive_csv`.

If you want to check the model using the provided archives, you can use archive_scan.py. 
E.g:
`python .\archive_scan.py .\test\nysh_archives.txt` - should scan entire archive.
`python .\archive_scan.py .\test\nysh_archives.txt --start 2021-04-01T12:34:30 --end 2021-04-01T12:36:30` - should scan a time window just around the event.

If you are interested in direct access to the archive scanning functions, you can take a look at the `stools.scan_traces` function. Although it is intended for internal use, and is not trivial to understand.

You can also load the model with `utils.seismo_load.load_performer` (or `load_cnn `or `load_gpd`) and operate it like any other Keras model. Input dimensions (by default) are 400.3. Basically, 4 seconds 3-channel 100 Hz waveform data.

If you are having trouble using our repo, you can specify what exactly you are trying to achieve and i can take a look at that.
